spring.application.name=period_tracker_springboot

#MySQL Connection Settings # I use port 3307 because that's the available port in my PC, just change it back to port 3306
spring.datasource.url=jdbc:mysql://localhost:3307/period_tracker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:yourPassword}

#JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Sending Code to E-Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=larrycabaelsoliva@gmail.com
spring.mail.password=fklkhwkubmhvvuqi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
